services:

  nn_training_kit:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: training
    restart: "no"
    volumes:
      - ./data:/app/data
      - ./configs:/app/configs
      - ./mlruns:/app/mlruns
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    tty: true
    command: python main.py

  mlflow:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: mlflow
    ports:
      - "5000:5000"
    volumes:
      - ./mlruns:/app/mlruns
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000
    command: mlflow ui --host 0.0.0.0
    depends_on:
      - nn_training_kit
