version: '3'

services:
  trainer:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: trainer
    restart: "no"
    volumes:
      - .:/app
    environment:
      - PYTHONPATH=/app
      - MLFLOW_TRACKING_URI=http://mlflow:5000
      - NVIDIA_VISIBLE_DEVICES=all
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    tty: true
    working_dir: /app
    command: python train_regression.py
    depends_on:
      - mlflow

  mlflow:
    container_name: mlflow-vis
    image: ghcr.io/mlflow/mlflow:latest
    ports:
      - "5000:5000"
    volumes:
      - ./mlruns:/mlflow
    command: mlflow server --host 0.0.0.0 --port 5000 